export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const INIT_EXPENSES = 'INIT_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const INIT_FIREBASE = 'INIT_FIREBASE';
export const CREATE_USER = 'CREATE_USER';
export const SET_USER = 'SET_USER';
